<a href="https://colab.research.google.com/github/MiguelUTEC26/etl-data-pipeline-2534562019/blob/main/B_productos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlalchemy psycopg2-binary
from sqlalchemy import create_engine
import pandas as pd
url = "https://raw.githubusercontent.com/MiguelUTEC26/etl-data-pipeline-2534562019/refs/heads/main/raw/B_productos.csv"
df = pd.read_csv(url)

df.head()

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 49.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

  id_producto       producto  precio id_proveedor
0      PR1000       Router 0  625.11         P325
1      PR1001      Teclado 1   61.12          NaN
2      PR1002        Mouse 2  203.71         P305
3      PR1003      Teclado 3  886.95         P304
4      PR1004   Impresora 4   103.94         P304

In [2]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_producto   146 non-null    object
 1   producto      146 non-null    object
 2   precio        139 non-null    object
 3   id_proveedor  137 non-null    object
dtypes: object(4)
memory usage: 4.7+ KB

id_producto     0
producto        0
precio          7
id_proveedor    9
dtype: int64

In [65]:
B_productos = df.copy()

B_productos.columns = B_productos.columns.str.strip().str.lower()

for col in B_productos.select_dtypes(include='object').columns:
    B_productos[col] = B_productos[col].astype(str).str.strip()

B_productos = B_productos.replace(r'^\s*$', pd.NA, regex=True)

id_producto_valido = B_productos['id_producto'].notna()
producto_valido = B_productos['producto'].notna()

id_proveedor_valido = B_productos['id_proveedor'].notna() & \
                     (B_productos['id_proveedor'].astype(str).str.strip() != "") & \
                     (B_productos['id_proveedor'].astype(str).str.lower() != "nan")

precio_valido = ~pd.to_numeric(B_productos['precio'], errors='coerce').isna()

In [66]:
validos = B_productos[
    B_productos['id_producto'].notna() &
    B_productos['producto'].notna() &
    B_productos['precio'].notna() &
    B_productos['id_proveedor'].notna()
].copy()

In [67]:
rechazados = B_productos[
     id_proveedor_vacio|
    precio_no_numerico
].copy()

In [68]:
def motivo(row):

    motivos = []
    valor_id = str(row['id_proveedor']).strip()
    if pd.isna(row['id_proveedor']) or valor_id == "" or valor_id.lower() == "nan":
        motivos.append("id_proveedor_vacio")

    if pd.isna(row['precio']):
        motivos.append("precio_vacio")

    elif pd.to_numeric(row['precio'], errors='coerce') is pd.NA or pd.isna(pd.to_numeric(row['precio'], errors='coerce')):
        motivos.append("precio_formato invalido")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [69]:
rechazados.to_csv("B_productos_rejects.csv", index=False)
validos.to_csv("B_productos_curated.csv", index=False)

In [70]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_c7ck_user:kFoJ2P6ViVJGqvzaVHFeHuuMqEThO1y3@dpg-d6qu3vc50q8c73bpda60-a.oregon-postgres.render.com/etl_seguros_c7ck"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [71]:
validos.to_sql(
    'b_productos_curated',
    engine,
    if_exists='append',
    index=False
)
rechazados.to_sql(
    'b_productos_rejects',
    engine,
    if_exists='append',
    index=False
)

26

In [72]:
pd.read_sql(
"SELECT * FROM b_productos_curated LIMIT 10",
engine
)

  id_producto     producto  precio id_proveedor
0      PR1000     Router 0  625.11         P325
1      PR1001    Teclado 1   61.12          nan
2      PR1002      Mouse 2  203.71         P305
3      PR1003    Teclado 3  886.95         P304
4      PR1004  Impresora 4  103.94         P304
5      PR1005     Router 5  725.77         P322
6      PR1006     Webcam 6  298.19         P308
7      PR1007     Router 7  470.21         P334
8      PR1008  Disco SSD 8  349.99         P319
9      PR1009  Audífonos 9  430.03         P334

In [73]:
pd.read_sql(
"SELECT * FROM b_productos_rejects LIMIT 10",
engine
)

,id_producto,producto,precio,id_proveedor,motivo_rechazo
0,PR1001,Teclado 1,61.12,nan,id_proveedor_vacio
1,PR1012,Router 12,USD 681.85,P323,precio_formato invalido
2,PR1013,Disco SSD 13,573.88 dólares,P302,precio_formato invalido
3,PR1020,Proyector 20,nan,P313,precio_formato invalido
4,PR1021,Audífonos 21,nan,P333,precio_formato invalido
5,PR1023,Tablet 23,nan,P302,precio_formato invalido
6,PR1039,Escritorio 39,$ 114.44,P307,precio_formato invalido
7,PR1040,Audífonos 40,1101.19 dólares,P304,precio_formato invalido
8,PR1052,Mouse 52,303.35,nan,id_proveedor_vacio
9,PR1055,Mouse 55,nan,P332,precio_formato invalido